networks:
  backend-network:
    name: backend-network

volumes:
  model-data:
    driver: local
    name: model-data
  minio-data:
    driver: local
    name: minio-data
  postgres-data:
    driver: local
    name: postgres-data
