services:
  elasticsearch:
    image: elasticsearch:7.17.22
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - cluster.name=anime
      - node.name=anime
    expose:
      - "9200"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://elasticsearch:9200"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - backend-network

  es-service:
    build:
      context: ../../animeshki-backend/src/es-service
    container_name: es-service
    expose:
      - "8001"
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      - ES_URL=http://elasticsearch:9200
      - KAFKA_BOOTSTRAP_SERVER=kafka:9092
      - KAFKA_TOPIC=es-topic
    networks:
      - backend-network
