services:
  model-service:
    build:
      context: ../../animeshki-backend/src/model-service
      dockerfile: Dockerfile
    container_name: model-service
    expose:
      - MODEL_PORT
    volumes:
      - model-data:/root/bin/      
    environment:
      - MODEL_PORT
      - MODEL_TRAIN_NUM_THREADS
    networks:
      - backend-network
    restart: always
