services:
  minio-service:
    build:
      context: ../../animeshki-backend/src/minio-service/
      dockerfile: Dockerfile
    depends_on:
      - minio
    container_name: minio-service
    environment:
      - MINIO_SERVICE_INIT_MODE
      - MINIO_ROOT_USER
      - MINIO_ROOT_PASSWORD
      - MINIO_SERVICE_USER_NAME
      - MINIO_SERVICE_USER_PASSWORD
      - MINIO_SERVICE_BUCKET_NAME
    expose:
      - "8000"
    networks:
      - backend-network
    restart: always

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      - MINIO_ROOT_USER
      - MINIO_ROOT_PASSWORD
    expose:
      - "9000"
    volumes:
      - minio-data:/data  # Точка монтирования для хранения данных
    networks:
      - backend-network
    command: [ "server", "/data", "--console-address", ":9001" ]
    restart: always
