services:
  model-service:
    build:
      context: ../../animeshki-backend/src/model-service
      dockerfile: Dockerfile
    container_name: model-service
    expose:
      - "8000"
    volumes:
      - ../../animeshki-backend/src/model-service/bin:/root/bin
    environment:
      - MODEL_PORT
      - MODEL_TRAIN_NUM_THREADS
    networks:
      - backend-network
    restart: always
