services:
  postgres:
    image: postgres
    container_name: animeshki-postgres
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    expose:
      - "5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend-network

  minio-service:
    build:
      context: ./src/minio-service/
      dockerfile: Dockerfile
    depends_on:
      - minio
    container_name: minio-service
    environment:
      - MINIO_SERVICE_INIT_MODE
      - MINIO_ROOT_USER
      - MINIO_ROOT_PASSWORD
      - MINIO_SERVICE_USER_NAME
      - MINIO_SERVICE_USER_PASSWORD
      - MINIO_SERVICE_BUCKET_NAME
    expose:
      - "8000"
    networks:
      - backend-network
      - minio-service-network
    restart: always
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      - MINIO_ROOT_USER
      - MINIO_ROOT_PASSWORD
    ports:
      - "9001:9001"  # Порт для MinIO Console
    expose:
      - "9000"
    volumes:
      - minio-data:/data  # Точка монтирования для хранения данных
    networks:
      - minio-service-network
    command: [ "server", "/data", "--console-address", ":9001" ]
    restart: always

networks:
  backend-network:
    name: backend-network
  minio-service-network:
    name: minio-service-network

volumes:
  minio-data:
    driver: local
    name: minio-data
  postgres-data:
    driver: local
    name: postgres-data

